<?php
	/*
	Suspendisse arcu leo, ultrices non eleifend eget, euismod sit amet mi. Donec porta ante ut magna consectetur dictum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras euismod accumsan sem, eu posuere leo ornare ac. Integer id bibendum eros. Phasellus sodales lectus vitae cursus venenatis. Integer vitae lectus feugiat, pulvinar tellus vel, feugiat elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce posuere dui id purus porta fringilla. Aenean est arcu, consequat vel commodo sit amet, congue id est.

Curabitur sed neque ornare felis feugiat gravida. Aenean malesuada orci vitae finibus tincidunt. Ut maximus purus at massa efficitur dictum. Curabitur placerat arcu ac dui finibus commodo. Aliquam erat volutpat. Nunc sit amet pulvinar dui. Aliquam tempus venenatis ultrices. Morbi mollis tristique bibendum. Integer dapibus turpis et magna laoreet laoreet. Donec sed est interdum, efficitur ex id, ultricies felis. Proin vel est urna. Donec ultricies tellus nec neque vehicula tincidunt. Curabitur sollicitudin elit at risus faucibus blandit. In aliquam mauris eget condimentum efficitur.

Cras id tincidunt turpis. Donec ultricies elit ac nunc porttitor hendrerit. Sed et metus vitae mi tincidunt auctor. Morbi eget lacus eget lectus euismod hendrerit mollis quis mi. Sed vitae vestibulum turpis, eget volutpat diam. Phasellus id tempus nulla. Vestibulum at lectus nec lectus efficitur aliquam ut eu nisi. Vivamus dignissim in mauris vel ultrices. In congue augue in quam aliquam gravida. Donec accumsan, nisi a elementum aliquet, elit libero mattis diam, id sodales tortor diam a arcu.

Morbi lacinia mi ligula, vitae pharetra erat ornare eget. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin non eleifend ligula. Praesent pharetra magna id risus vulputate, nec pharetra ipsum vestibulum. Aenean luctus, lectus in dictum commodo, orci enim consequat quam, sit amet convallis nunc lectus in risus. Suspendisse luctus non metus euismod pharetra. Mauris luctus lorem diam, quis pharetra risus lobortis in. Sed malesuada finibus ultrices. Vivamus varius nulla eget felis venenatis, vitae dapibus velit vulputate. Etiam vitae pellentesque purus. Morbi facilisis est purus, vitae tincidunt sapien feugiat eget. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur finibus vulputate turpis. Fusce vehicula, ipsum in egestas posuere, tortor lectus pharetra est, vitae placerat nibh dui sit amet nulla. Integer dolor velit, pellentesque non quam in, dignissim semper lectus.

Sed eget ante ipsum. Curabitur venenatis turpis vitae turpis elementum iaculis. Quisque nibh neque, ultricies eu convallis vel, varius eu enim. Curabitur metus diam, aliquam vel purus nec, iaculis imperdiet erat. Mauris condimentum, nulla ut ornare sodales, dolor augue tristique tortor, quis congue augue orci quis neque. In aliquam felis mi, a porta erat facilisis eget. Aenean vehicula, elit vel auctor vulputate, ex augue luctus sem, sit amet eleifend mauris nisi eu odio.

*/

	echo file_get_contents("http://www.telize.com/ip");
/*
Suspendisse arcu leo, ultrices non eleifend eget, euismod sit amet mi. Donec porta ante ut magna consectetur dictum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras euismod accumsan sem, eu posuere leo ornare ac. Integer id bibendum eros. Phasellus sodales lectus vitae cursus venenatis. Integer vitae lectus feugiat, pulvinar tellus vel, feugiat elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce posuere dui id purus porta fringilla. Aenean est arcu, consequat vel commodo sit amet, congue id est.

Curabitur sed neque ornare felis feugiat gravida. Aenean malesuada orci vitae finibus tincidunt. Ut maximus purus at massa efficitur dictum. Curabitur placerat arcu ac dui finibus commodo. Aliquam erat volutpat. Nunc sit amet pulvinar dui. Aliquam tempus venenatis ultrices. Morbi mollis tristique bibendum. Integer dapibus turpis et magna laoreet laoreet. Donec sed est interdum, efficitur ex id, ultricies felis. Proin vel est urna. Donec ultricies tellus nec neque vehicula tincidunt. Curabitur sollicitudin elit at risus faucibus blandit. In aliquam mauris eget condimentum efficitur.

Cras id tincidunt turpis. Donec ultricies elit ac nunc porttitor hendrerit. Sed et metus vitae mi tincidunt auctor. Morbi eget lacus eget lectus euismod hendrerit mollis quis mi. Sed vitae vestibulum turpis, eget volutpat diam. Phasellus id tempus nulla. Vestibulum at lectus nec lectus efficitur aliquam ut eu nisi. Vivamus dignissim in mauris vel ultrices. In congue augue in quam aliquam gravida. Donec accumsan, nisi a elementum aliquet, elit libero mattis diam, id sodales tortor diam a arcu.

Morbi lacinia mi ligula, vitae pharetra erat ornare eget. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin non eleifend ligula. Praesent pharetra magna id risus vulputate, nec pharetra ipsum vestibulum. Aenean luctus, lectus in dictum commodo, orci enim consequat quam, sit amet convallis nunc lectus in risus. Suspendisse luctus non metus euismod pharetra. Mauris luctus lorem diam, quis pharetra risus lobortis in. Sed malesuada finibus ultrices. Vivamus varius nulla eget felis venenatis, vitae dapibus velit vulputate. Etiam vitae pellentesque purus. Morbi facilisis est purus, vitae tincidunt sapien feugiat eget. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur finibus vulputate turpis. Fusce vehicula, ipsum in egestas posuere, tortor lectus pharetra est, vitae placerat nibh dui sit amet nulla. Integer dolor velit, pellentesque non quam in, dignissim semper lectus.

Sed eget ante ipsum. Curabitur venenatis turpis vitae turpis elementum iaculis. Quisque nibh neque, ultricies eu convallis vel, varius eu enim. Curabitur metus diam, aliquam vel purus nec, iaculis imperdiet erat. Mauris condimentum, nulla ut ornare sodales, dolor augue tristique tortor, quis congue augue orci quis neque. In aliquam felis mi, a porta erat facilisis eget. Aenean vehicula, elit vel auctor vulputate, ex augue luctus sem, sit amet eleifend mauris nisi eu odio.

*/

?>