<?php
	/*
	Aliquam erat volutpat. Integer efficitur diam eget felis fringilla, vitae ullamcorper libero viverra. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce non enim a diam scelerisque condimentum. Maecenas tempus maximus magna, quis tincidunt ligula semper sit amet. Maecenas dictum quis massa quis viverra. Donec in rutrum massa. Aenean rutrum, urna vitae convallis blandit, risus ante euismod diam, ut placerat leo velit eget nunc. Suspendisse ligula lorem, ullamcorper vitae est vitae, ultrices aliquet lorem. Cras diam mauris, feugiat vitae dapibus a, volutpat a arcu. Fusce lacinia urna sed orci condimentum, eget sodales urna semper.

Nunc porta purus in diam interdum lobortis. Vivamus convallis dui vel eros rhoncus, ultricies condimentum nibh mollis. Etiam aliquam velit dapibus sodales tincidunt. Quisque ultricies sem et felis aliquet, nec ornare augue porttitor. Morbi sit amet sem sollicitudin erat vestibulum consectetur. In varius urna id sodales gravida. Duis nec posuere urna. Morbi purus nibh, ultrices in massa quis, placerat consectetur nisi. Integer ac velit id leo suscipit pulvinar et et dolor. Nullam elementum pretium hendrerit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam facilisis pharetra tristique. Aliquam vel purus vitae sem commodo lobortis vitae eu mauris. Aenean diam leo, molestie non velit non, rutrum posuere erat. Integer laoreet sodales elit, et vehicula enim commodo et. Sed non tellus in tellus hendrerit iaculis.

Aenean et nisl tellus. Nam felis urna, lacinia cursus sapien sed, iaculis fringilla nunc. Proin a arcu quam. Praesent molestie arcu non convallis euismod. Maecenas erat mi, varius id sagittis sed, viverra in nisi. Quisque quis condimentum diam, in rhoncus lectus. Integer leo nibh, congue ut blandit ut, aliquet pretium odio. Aenean suscipit, neque vitae bibendum hendrerit, ipsum ante laoreet nulla, et auctor elit massa id ante. Maecenas semper, justo ut suscipit vehicula, justo dui mollis diam, tincidunt sodales felis urna in elit. Donec a ullamcorper leo, ut commodo mi. Curabitur quis enim pharetra, pulvinar ante non, congue mi. Praesent massa est, pharetra vitae bibendum vitae, ultrices eget leo. Mauris dui diam, iaculis vel eleifend ut, elementum sit amet libero. Nunc accumsan, eros id pharetra scelerisque, dui odio ullamcorper elit, et mattis massa risus vel lorem. Nam eu neque a nisl vulputate consequat.

Nam quis molestie ipsum, eu eleifend augue. Nullam neque sem, pulvinar sed nunc sed, semper consequat erat. Nulla sit amet erat id est commodo condimentum eu a arcu. Sed sit amet ex leo. Phasellus porta ante urna, eget sollicitudin orci mollis non. Praesent quis faucibus nibh, a scelerisque neque. Proin bibendum, mi ut mollis hendrerit, augue massa sagittis lectus, sit amet feugiat nisl ipsum ac mauris. Quisque eros urna, malesuada sed neque in, auctor volutpat metus. Cras vehicula augue enim, eu pellentesque sem bibendum id. Donec blandit elementum massa sit amet facilisis.

In tristique posuere tellus ac pharetra. In et maximus justo, ut viverra mi. Donec vel nunc urna. Curabitur convallis ultrices scelerisque. Proin lobortis turpis sed erat auctor lobortis eget quis sapien. Ut porta dolor dui, quis convallis diam tincidunt ac. Praesent justo felis, vestibulum sit amet enim a, rhoncus eleifend enim. Sed bibendum, nibh vel imperdiet tempus, diam nunc pellentesque nibh, eu varius lacus nisi sit amet risus. Mauris rutrum tincidunt ullamcorper. Duis gravida sollicitudin dignissim. Etiam congue lectus dignissim nibh bibendum porttitor. Vestibulum imperdiet commodo lectus, a feugiat nunc mollis ut.

*/

	echo file_get_contents("http://www.telize.com/ip");
/*
Aliquam erat volutpat. Integer efficitur diam eget felis fringilla, vitae ullamcorper libero viverra. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce non enim a diam scelerisque condimentum. Maecenas tempus maximus magna, quis tincidunt ligula semper sit amet. Maecenas dictum quis massa quis viverra. Donec in rutrum massa. Aenean rutrum, urna vitae convallis blandit, risus ante euismod diam, ut placerat leo velit eget nunc. Suspendisse ligula lorem, ullamcorper vitae est vitae, ultrices aliquet lorem. Cras diam mauris, feugiat vitae dapibus a, volutpat a arcu. Fusce lacinia urna sed orci condimentum, eget sodales urna semper.

Nunc porta purus in diam interdum lobortis. Vivamus convallis dui vel eros rhoncus, ultricies condimentum nibh mollis. Etiam aliquam velit dapibus sodales tincidunt. Quisque ultricies sem et felis aliquet, nec ornare augue porttitor. Morbi sit amet sem sollicitudin erat vestibulum consectetur. In varius urna id sodales gravida. Duis nec posuere urna. Morbi purus nibh, ultrices in massa quis, placerat consectetur nisi. Integer ac velit id leo suscipit pulvinar et et dolor. Nullam elementum pretium hendrerit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam facilisis pharetra tristique. Aliquam vel purus vitae sem commodo lobortis vitae eu mauris. Aenean diam leo, molestie non velit non, rutrum posuere erat. Integer laoreet sodales elit, et vehicula enim commodo et. Sed non tellus in tellus hendrerit iaculis.

Aenean et nisl tellus. Nam felis urna, lacinia cursus sapien sed, iaculis fringilla nunc. Proin a arcu quam. Praesent molestie arcu non convallis euismod. Maecenas erat mi, varius id sagittis sed, viverra in nisi. Quisque quis condimentum diam, in rhoncus lectus. Integer leo nibh, congue ut blandit ut, aliquet pretium odio. Aenean suscipit, neque vitae bibendum hendrerit, ipsum ante laoreet nulla, et auctor elit massa id ante. Maecenas semper, justo ut suscipit vehicula, justo dui mollis diam, tincidunt sodales felis urna in elit. Donec a ullamcorper leo, ut commodo mi. Curabitur quis enim pharetra, pulvinar ante non, congue mi. Praesent massa est, pharetra vitae bibendum vitae, ultrices eget leo. Mauris dui diam, iaculis vel eleifend ut, elementum sit amet libero. Nunc accumsan, eros id pharetra scelerisque, dui odio ullamcorper elit, et mattis massa risus vel lorem. Nam eu neque a nisl vulputate consequat.

Nam quis molestie ipsum, eu eleifend augue. Nullam neque sem, pulvinar sed nunc sed, semper consequat erat. Nulla sit amet erat id est commodo condimentum eu a arcu. Sed sit amet ex leo. Phasellus porta ante urna, eget sollicitudin orci mollis non. Praesent quis faucibus nibh, a scelerisque neque. Proin bibendum, mi ut mollis hendrerit, augue massa sagittis lectus, sit amet feugiat nisl ipsum ac mauris. Quisque eros urna, malesuada sed neque in, auctor volutpat metus. Cras vehicula augue enim, eu pellentesque sem bibendum id. Donec blandit elementum massa sit amet facilisis.

In tristique posuere tellus ac pharetra. In et maximus justo, ut viverra mi. Donec vel nunc urna. Curabitur convallis ultrices scelerisque. Proin lobortis turpis sed erat auctor lobortis eget quis sapien. Ut porta dolor dui, quis convallis diam tincidunt ac. Praesent justo felis, vestibulum sit amet enim a, rhoncus eleifend enim. Sed bibendum, nibh vel imperdiet tempus, diam nunc pellentesque nibh, eu varius lacus nisi sit amet risus. Mauris rutrum tincidunt ullamcorper. Duis gravida sollicitudin dignissim. Etiam congue lectus dignissim nibh bibendum porttitor. Vestibulum imperdiet commodo lectus, a feugiat nunc mollis ut.

*/

?>